---
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - "/srv/docker/jellyfin:/config"
      - "cache:/cache"
      - "/mnt/external/media:/media"
    networks:
     - swag_network
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=url
      - homepage.description=Home Media Streaming
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=api_key
      - homepage.widget.enableBlocks=true
      - homepage.widget.enableNowPlaying=true
      - homepage.widget.enableUser=true
      - homepage.widget.showEpisodeNumber=true
      - homepage.widget.expandOneStreamToTwoRows=true

volumes:
  cache:
    external: false

networks:
  swag_network:
    name: swag_network
    external: true
...
