---
services:
  swag:
    container_name: swag
    hostname: raspberrypi.swag
    image: lscr.io/linuxserver/swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    env_file:
      - stack.env
    volumes:
      - /srv/docker/swag:/config
    ports:
      - 443:443
    networks:
      - swag_network
    healthcheck:
      test: "curl --fail http://localhost"

networks:
  swag_network:
    name: swag_network
    external: true
...
